name: Desarrollo Seguro

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  desarrollo-seguro:
    name: Análisis SonarCloud + Semgrep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Instalar Semgrep
        run: |
          pip install semgrep

      - name: Ejecutar Semgrep
        run: semgrep --config=auto .
