name: Desarrollo Seguro

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sonarqube-analysis:
    name: Análisis SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
